const actionTypes = {
  FETCH_TODO_ITEMS: 'FETCH_TODO_ITEMS',
  FETCH_WEATHER: 'FETCH_WEATHER',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export default {
  actionTypes,
};
